'use client';

import { useState, useEffect, useRef } from 'react';
import type { ScoreResponse, PremiumResponse } from '@/lib/schemas';
import PayWithRazorpay from './PayWithRazorpay';

interface ScoreResultsProps {
  result:          ScoreResponse;
  isDemo?:         boolean;
  isAdmin?:        boolean;
  tier?:           string;
  creditUsed?:     boolean;
  premiumResult?:  PremiumResponse | null;
  onPremiumReady?: (r: PremiumResponse) => void;
  resumeText?:     string;
  jobDescription?: string;
  onReset:         () => void;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const SECTION_LABELS: Record<string, string> = {
  contact:    'Contact & Links',
  summary:    'Summary / Objective',
  skills:     'Skills Section',
  experience: 'Work Experience',
  education:  'Education',
  projects:   'Projects',
  formatting: 'Formatting & ATS',
};

function ringColor(s: number)   { return s >= 70 ? '#10D98A' : s >= 50 ? '#4080FF' : '#F06060'; }
function scoreColor(v: number)  {
  if (v >= 7.5) return { text: 'text-success', bar: '#10D98A' };
  if (v >= 5)   return { text: 'text-accent',  bar: '#4080FF' };
  return               { text: 'text-danger',  bar: '#F06060' };
}
function matchColor(p: number)  { return p >= 75 ? 'text-success' : p >= 50 ? 'text-warning' : 'text-danger'; }
function matchBg(p: number)     { return p >= 75 ? 'bg-success-bg border-success-border' : p >= 50 ? 'bg-warning-bg border-warning-border' : 'bg-danger-bg border-danger-border'; }

function scoreLabel(s: number): { label: string; color: string; bg: string } {
  if (s >= 78) return { label: 'Strong',        color: 'text-success', bg: 'bg-success-bg border-success-border' };
  if (s >= 62) return { label: 'Average',       color: 'text-accent',  bg: 'bg-accent-glow border-accent-border' };
  if (s >= 45) return { label: 'Below Average', color: 'text-warning', bg: 'bg-warning-bg border-warning-border' };
  return              { label: 'Poor',          color: 'text-danger',  bg: 'bg-danger-bg border-danger-border' };
}

function impactMessage(verdict: string, jdMatch?: number): { text: string; color: string; bg: string } {
  if (verdict === 'Fail')
    return { text: 'High risk: ATS is likely rejecting your resume before a recruiter sees it', color: 'text-danger', bg: 'bg-danger-bg border-danger-border' };
  if (verdict === 'Borderline' || (jdMatch !== undefined && jdMatch < 55))
    return { text: 'At risk: Low interview chances unless critical issues are fixed now', color: 'text-warning', bg: 'bg-warning-bg border-warning-border' };
  return { text: 'ATS-safe: Your resume reaches human reviewers — now optimise for interviews', color: 'text-success', bg: 'bg-success-bg border-success-border' };
}

function atsBadge(v: string) {
  if (v === 'Pass')       return { cls: 'bg-success-bg text-success border-success-border', icon: '✓' };
  if (v === 'Borderline') return { cls: 'bg-warning-bg text-warning border-warning-border', icon: '~' };
  return                         { cls: 'bg-danger-bg text-danger border-danger-border',   icon: '✗' };
}

function hasMetric(text: string) { return /\d+/.test(text); }
function keywordsInText(text: string, keywords: string[]): string[] {
  return keywords.filter(k => text.toLowerCase().includes(k.toLowerCase()));
}

function buildDownloadText(result: ScoreResponse): string {
  const lines: string[] = [
    'SCRYVEME — RESUME IMPROVEMENT REPORT',
    '=====================================',
    `Score: ${result.overall}/100   ATS: ${result.ats_verdict}`,
    result.projected_score ? `Projected after fixes: ${result.projected_score}/100` : '',
    '',
    'PRIORITY FIXES',
    '--------------',
    ...result.improvements.map((m, i) => `${i + 1}. ${m}`),
    '',
  ];
  if (result.improved_bullets?.length) {
    lines.push('REWRITTEN BULLET POINTS', '-----------------------');
    result.improved_bullets.forEach((b, i) => {
      lines.push(`• ${b}`);
      if (result.bullet_explanations?.[i]) lines.push(`  → Why: ${result.bullet_explanations[i]}`);
      lines.push('');
    });
  }
  if (result.critical_keywords?.length) {
    lines.push('CRITICAL KEYWORDS TO ADD', '------------------------');
    lines.push(result.critical_keywords.join(', '), '');
  }
  if (result.optional_keywords?.length) {
    lines.push('OPTIONAL KEYWORDS', '-----------------');
    lines.push(result.optional_keywords.join(', '), '');
  }
  lines.push('', '— Generated by scryveMe (scryveme.in)');
  return lines.filter(Boolean).join('\n');
}

// ── Collapsible section ───────────────────────────────────────────────────────

function Collapsible({ title, icon, defaultOpen = true, children, delay = '0ms' }: {
  title: string; icon: React.ReactNode; defaultOpen?: boolean;
  children: React.ReactNode; delay?: string;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="card result-card overflow-hidden" style={{ animationDelay: delay }}>
      <button
        onClick={() => setOpen(o => !o)}
        className="flex items-center justify-between w-full text-left"
      >
        <div className="flex items-center gap-2.5">{icon}<span className="section-label">{title}</span></div>
        <svg
          width="16" height="16" viewBox="0 0 16 16" fill="none"
          className={`text-dim transition-transform duration-200 flex-shrink-0 ${open ? 'rotate-180' : ''}`}
        >
          <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>
      {open && <div className="mt-4">{children}</div>}
    </div>
  );
}

// ── Upgrade gate ─────────────────────────────────────────────────────────────

function UpgradeGate({ title, description, hint }: { title: string; description: string; hint?: string }) {
  return (
    <div className="rounded-xl border border-border bg-surface p-4 flex items-start gap-4">
      <div className="w-8 h-8 rounded-xl bg-accent-glow border border-accent-border flex items-center justify-center flex-shrink-0 mt-0.5">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
          <rect x="2" y="6.5" width="10" height="6.5" rx="1.5" stroke="#4080FF" strokeWidth="1.3" />
          <path d="M4.5 6.5V4.5a2.5 2.5 0 015 0v2" stroke="#4080FF" strokeWidth="1.3" strokeLinecap="round" />
        </svg>
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-display font-semibold text-primary mb-1">{title}</p>
        <p className="text-xs text-secondary leading-relaxed mb-3">{description}</p>
        {hint && <p className="text-xs text-dim italic mb-3">{hint}</p>}
        <a
          href="/pricing"
          className="inline-flex items-center gap-1.5 text-xs font-display font-bold text-accent border border-accent-border bg-accent-glow px-3 py-1.5 rounded-lg hover:brightness-110 transition-all"
        >
          Get full analysis — ₹19 →
        </a>
      </div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

const circumference = 2 * Math.PI * 54;

export default function ScoreResults({
  result, isDemo, isAdmin, tier, creditUsed, premiumResult, onPremiumReady, resumeText, jobDescription, onReset,
}: ScoreResultsProps) {
  const {
    overall, scores, strengths, improvements, india_specific_tips,
    ats_verdict, jd_match_percent, critical_keywords, optional_keywords,
    missing_keywords, improved_bullets, bullet_explanations, projected_score,
  } = result;

  // Paid access: used a credit, on pro/elite tier, or demo mode
  const proAccess = tier === 'pro' || tier === 'elite' || creditUsed === true || isDemo === true;
  const hasPremium = !!premiumResult;

  const [copied, setCopied]         = useState<number | null>(null);
  const [copiedAll, setCopiedAll]   = useState(false);
  const [showSticky, setShowSticky] = useState(false);
  const [premiumError, setPremiumError] = useState('');
  const [premiumLoading, setPremiumLoading] = useState(false);
  const heroRef = useRef<HTMLDivElement>(null);

  const offset  = circumference - (overall / 100) * circumference;
  const ats     = atsBadge(ats_verdict);
  const slabel  = scoreLabel(overall);
  const impact  = impactMessage(ats_verdict, jd_match_percent);

  // Show sticky CTA after scrolling past hero
  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;
    const obs = new IntersectionObserver(([e]) => setShowSticky(!e.isIntersecting), { threshold: 0 });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  function copyBullet(text: string, i: number) {
    navigator.clipboard.writeText(text).then(() => { setCopied(i); setTimeout(() => setCopied(null), 2000); });
  }

  function copyAllImprovements() {
    const text = improvements.map((m, i) => `${i + 1}. ${m}`).join('\n\n');
    navigator.clipboard.writeText(text).then(() => { setCopiedAll(true); setTimeout(() => setCopiedAll(false), 2500); });
  }

  function downloadReport() {
    const blob = new Blob([buildDownloadText(result)], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = 'scryveme-resume-report.txt'; a.click();
    URL.revokeObjectURL(url);
  }

  async function fetchPremiumEnhancement() {
    if (!resumeText) return;
    setPremiumLoading(true);
    setPremiumError('');
    try {
      const res = await fetch('/api/premium', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ resumeText, jobDescription, scoreData: result }),
      });
      const data = await res.json();
      if (!res.ok) {
        setPremiumError(data.error ?? 'Premium enhancement failed. Try again.');
        return;
      }
      onPremiumReady?.(data);
    } catch {
      setPremiumError('Network error. Please try again.');
    } finally {
      setPremiumLoading(false);
    }
  }

  function downloadPremiumPDF() {
    if (!premiumResult) return;
    const lines: string[] = [
      'SCRYVEME — JOB-READY RESUME ENHANCEMENT',
      '=========================================',
      `Original score: ${overall}/100   ATS: ${ats_verdict}`,
      '',
      'KEY IMPROVEMENTS MADE',
      '---------------------',
      ...premiumResult.key_changes.map((c, i) => `${i + 1}. ${c}`),
      '',
    ];
    if (premiumResult.section_rewrites.summary) {
      lines.push('IMPROVED SUMMARY', '----------------', premiumResult.section_rewrites.summary, '');
    }
    if (premiumResult.section_rewrites.skills) {
      lines.push('IMPROVED SKILLS', '---------------', premiumResult.section_rewrites.skills, '');
    }
    if (premiumResult.all_improved_bullets.length) {
      lines.push('REWRITTEN BULLET POINTS', '-----------------------');
      premiumResult.all_improved_bullets.forEach((b, i) => {
        lines.push(`• ${b}`);
        if (premiumResult.all_bullet_explanations[i]) lines.push(`  → ${premiumResult.all_bullet_explanations[i]}`);
        lines.push('');
      });
    }
    if (premiumResult.section_rewrites.experience) {
      lines.push('EXPERIENCE HIGHLIGHTS', '---------------------', premiumResult.section_rewrites.experience, '');
    }
    if (premiumResult.section_rewrites.projects) {
      lines.push('PROJECTS', '--------', premiumResult.section_rewrites.projects, '');
    }
    lines.push('', '— Generated by scryveMe Premium (scryveme.in)');

    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html><head><title>scryveMe Premium Resume</title>
      <style>
        body { font-family: 'Courier New', monospace; font-size: 13px; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111; }
        h1 { font-size: 16px; border-bottom: 2px solid #111; padding-bottom: 6px; }
        pre { white-space: pre-wrap; word-wrap: break-word; }
      </style></head>
      <body><pre>${lines.join('\n').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
      <script>window.onload = function() { window.print(); }</script>
      </body></html>
    `);
    win.document.close();
  }

  // Merge keywords: prefer critical/optional split, fallback to missing_keywords
  const critKW = critical_keywords ?? (missing_keywords?.slice(0, 6) ?? []);
  const optKW  = optional_keywords ?? (missing_keywords?.slice(6) ?? []);

  const whatsappText = `https://wa.me/?text=${encodeURIComponent(
    `I just scored ${overall}/100 on scryveMe's free AI resume checker! 🎯\nATS verdict: ${ats_verdict}\n\nTry it free at scryveme.in — built for Indian job seekers 🇮🇳`
  )}`;

  return (
    <>
      <div className="space-y-4 pb-24">

        {/* Demo banner */}
        {isDemo && (
          <div className="rounded-xl border border-accent-border bg-accent-glow px-4 py-3 flex items-start gap-3 text-sm">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="flex-shrink-0 mt-0.5">
              <circle cx="8" cy="8" r="7" stroke="#4080FF" strokeWidth="1.5" />
              <path d="M8 5v3.5M8 10.5v.5" stroke="#4080FF" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
            <span>
              <span className="text-accent font-display font-semibold">Demo mode — </span>
              <span className="text-secondary">Sample resume results. Click &ldquo;Score my own resume&rdquo; below to analyse yours.</span>
            </span>
          </div>
        )}

        {/* ── Hero: Score ── */}
        <div ref={heroRef} className="card-glow result-card" style={{ animationDelay: '0ms' }}>
          <div className="flex flex-col sm:flex-row items-center gap-6">

            {/* Ring */}
            <div className="relative flex-shrink-0">
              <svg width="124" height="124" viewBox="0 0 124 124" className="-rotate-90">
                <circle cx="62" cy="62" r="54" fill="none" stroke="#1E3050" strokeWidth="9" />
                <circle cx="62" cy="62" r="54" fill="none" stroke={ringColor(overall)} strokeWidth="9"
                  strokeLinecap="round" strokeDasharray={circumference}
                  className="score-ring-progress"
                  style={{ '--target-offset': offset } as React.CSSProperties}
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="font-display font-bold text-3xl text-primary leading-none">{overall}</span>
                <span className="text-xs text-dim mt-0.5">/ 100</span>
              </div>
            </div>

            {/* Meta */}
            <div className="flex-1 text-center sm:text-left">
              <p className="text-secondary text-xs font-display font-semibold uppercase tracking-widest mb-1">Resume Score</p>

              {/* Score label */}
              <div className="flex items-center gap-2 justify-center sm:justify-start mb-3">
                <span className={`font-display font-bold text-2xl ${slabel.color}`}>{slabel.label}</span>
                <span className={`tag text-xs ${slabel.bg} ${slabel.color}`}>{overall}/100</span>
              </div>

              {/* Score context benchmarks */}
              <div className="flex flex-wrap gap-3 text-xs mb-3 justify-center sm:justify-start">
                <span className="text-dim">Avg for this role: <span className="text-secondary font-semibold">58</span></span>
                <span className="text-dim">Top candidates: <span className="text-success font-semibold">75–85</span></span>
              </div>

              <div className="flex flex-wrap gap-2 justify-center sm:justify-start">
                <span className={`tag ${ats.cls}`}>{ats.icon} ATS: {ats_verdict}</span>
                {jd_match_percent !== undefined && (
                  <span className={`tag ${matchBg(jd_match_percent)}`}>
                    <span className={matchColor(jd_match_percent)}>◎ JD Match: {jd_match_percent}%</span>
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Impact message */}
          <div className={`mt-4 px-3 py-2.5 rounded-xl border flex items-start gap-2 text-sm ${impact.bg}`}>
            <span className={`font-bold flex-shrink-0 mt-0.5 ${impact.color}`}>→</span>
            <span className={impact.color}>{impact.text}</span>
          </div>

          {/* JD match bar */}
          {jd_match_percent !== undefined && (
            <div className="mt-4 pt-4 border-t border-border">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs text-secondary font-display font-semibold">Job Description Match</span>
                <span className={`text-xs font-display font-bold ${matchColor(jd_match_percent)}`}>
                  {jd_match_percent}% — {jd_match_percent >= 75 ? 'Strong' : jd_match_percent >= 50 ? 'Partial' : 'Weak'} match
                </span>
              </div>
              <div className="h-2 bg-surface rounded-full overflow-hidden">
                <div className="h-full rounded-full score-bar"
                  style={{ width: `${jd_match_percent}%`, backgroundColor: jd_match_percent >= 75 ? '#10D98A' : jd_match_percent >= 50 ? '#F59E0B' : '#F06060', '--bar-delay': '200ms' } as React.CSSProperties}
                />
              </div>
            </div>
          )}
        </div>

        {/* ── Projected Score ── */}
        {projected_score !== undefined && proAccess && (
          <div
            className="rounded-2xl border border-accent-border px-5 py-4 flex items-center justify-between result-card"
            style={{
              animationDelay: '50ms',
              background: 'linear-gradient(135deg, rgba(64,128,255,0.12) 0%, rgba(56,189,248,0.06) 100%)',
              boxShadow: '0 2px 20px rgba(0,0,0,0.5), 0 0 40px rgba(64,128,255,0.1), inset 0 1px 0 rgba(255,255,255,0.06)',
            }}
          >
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl bg-accent flex items-center justify-center flex-shrink-0" style={{ boxShadow: '0 4px 12px rgba(64,128,255,0.4)' }}>
                <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                  <path d="M2 11L5.5 7.5l2.5 2.5L13 3" stroke="white" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <div>
                <p className="text-sm font-display font-bold text-primary">Apply all fixes</p>
                <p className="text-xs text-secondary mt-0.5">Estimated score after improvements</p>
              </div>
            </div>
            <div className="text-right flex-shrink-0 ml-4">
              <p className="font-display font-bold text-3xl text-accent leading-none">{projected_score}<span className="text-sm font-normal text-secondary">/100</span></p>
              <p className="text-xs text-success font-semibold mt-0.5">+{projected_score - overall} points</p>
            </div>
          </div>
        )}

        {/* ── Projected Score gate (free tier) ── */}
        {!proAccess && (
          <div className="card result-card" style={{ animationDelay: '50ms' }}>
            <UpgradeGate
              title="Projected score after fixes"
              description="See exactly what score you could reach if you apply all the improvements — so you know which fixes matter most."
              hint={projected_score ? `Based on your resume, you could reach ${projected_score}/100 with the recommended changes.` : undefined}
            />
          </div>
        )}

        {/* ── Keywords ── */}
        {(critKW.length > 0 || optKW.length > 0) && (
          <div className="card result-card" style={{ animationDelay: '100ms' }}>
            <div className="flex items-center gap-2.5 mb-4">
              <div className="w-7 h-7 rounded-lg bg-danger-bg border border-danger-border flex items-center justify-center flex-shrink-0">
                <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                  <path d="M6.5 2v4.5M6.5 8.5v.5" stroke="#F06060" strokeWidth="1.6" strokeLinecap="round" />
                </svg>
              </div>
              <div>
                <h2 className="section-label leading-none">Missing keywords</h2>
                <p className="text-xs text-dim mt-0.5">Add these to pass JD screening</p>
              </div>
            </div>

            {proAccess ? (
              <>
                {critKW.length > 0 && (
                  <div className="mb-3">
                    <p className="text-xs font-display font-semibold text-danger uppercase tracking-wider mb-2">
                      ⚠ Critical — ATS will reject without these
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {critKW.map((kw, i) => (
                        <span key={i} className="inline-flex items-center gap-1.5 bg-danger-bg border border-danger-border text-danger text-xs font-display font-semibold px-3 py-1.5 rounded-full">
                          <svg width="8" height="8" viewBox="0 0 8 8" fill="none"><path d="M1.5 1.5l5 5M6.5 1.5l-5 5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" /></svg>
                          {kw}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {optKW.length > 0 && (
                  <div>
                    <p className="text-xs font-display font-semibold text-warning uppercase tracking-wider mb-2">
                      Optional — strengthen your match
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {optKW.map((kw, i) => (
                        <span key={i} className="inline-flex items-center gap-1.5 bg-warning-bg border border-warning-border text-warning text-xs font-display font-semibold px-3 py-1.5 rounded-full">
                          {kw}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </>
            ) : (
              <UpgradeGate
                title={`${critKW.length} critical + ${optKW.length} optional keywords missing`}
                description="Your resume is missing keywords that ATS systems actively filter for. Pro shows you exactly which ones — and which are dealbreakers vs nice-to-haves."
              />
            )}
          </div>
        )}

        {/* ── Strengths (collapsible on mobile) ── */}
        <Collapsible
          delay="160ms"
          defaultOpen={true}
          title="What's working"
          icon={
            <div className="w-7 h-7 rounded-lg bg-success-bg border border-success-border flex items-center justify-center flex-shrink-0">
              <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                <path d="M1.5 6.5L5 10L11.5 3" stroke="#10D98A" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
          }
        >
          <ul className="space-y-2">
            {strengths.map((s, i) => (
              <li key={i} className="flex items-start gap-3 text-sm font-body text-primary p-3 rounded-xl bg-surface border border-border">
                <span className="text-success font-bold flex-shrink-0 mt-0.5">✓</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </Collapsible>

        {/* ── Improvements ── */}
        <div className="card result-card" style={{ animationDelay: '220ms' }}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-warning-bg border border-warning-border flex items-center justify-center flex-shrink-0">
                <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                  <path d="M6.5 2v4.5M6.5 8.5v.5" stroke="#F59E0B" strokeWidth="1.6" strokeLinecap="round" />
                </svg>
              </div>
              <div>
                <h2 className="section-label leading-none">Priority fixes</h2>
                <p className="text-xs text-dim mt-0.5">Apply these to significantly raise your score</p>
              </div>
            </div>
            <button
              onClick={copyAllImprovements}
              className="flex-shrink-0 text-xs font-display font-semibold text-accent border border-accent-border bg-accent-glow px-3 py-1.5 rounded-lg hover:brightness-110 transition-all"
            >
              {copiedAll ? '✓ Copied!' : 'Copy all'}
            </button>
          </div>
          <ul className="space-y-2">
            {improvements.map((imp, i) => (
              <li key={i} className="flex items-start gap-3 text-sm p-3 rounded-xl bg-surface border border-border">
                <span className="w-5 h-5 rounded-full bg-warning-bg border border-warning-border flex items-center justify-center flex-shrink-0 mt-0.5 text-xs font-display font-bold text-warning">
                  {i + 1}
                </span>
                <span className="text-primary">{imp}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* ── Premium CTA (shown after paid analysis, before premium results) ── */}
        {proAccess && !hasPremium && !isDemo && (
          <div
            className="card result-card border border-accent-border"
            style={{
              animationDelay: '260ms',
              background: 'linear-gradient(135deg, rgba(64,128,255,0.08) 0%, rgba(56,189,248,0.04) 100%)',
            }}
          >
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-accent flex items-center justify-center flex-shrink-0" style={{ boxShadow: '0 4px 12px rgba(64,128,255,0.35)' }}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                  <path d="M2 16l3-1.5L15 4.5a2 2 0 00-2.5-2.5L2 13.5 2 16z" stroke="white" strokeWidth="1.5" strokeLinejoin="round" />
                </svg>
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <p className="text-primary text-sm font-display font-bold">Get a job-ready resume</p>
                  <span className="text-xs bg-accent text-white px-2 py-0.5 rounded-full font-display font-bold">Premium</span>
                </div>
                <p className="text-secondary text-xs mb-3 leading-relaxed">
                  AI rewrites all your bullet points, optimises your summary and skills, and gives you a downloadable resume ready to send.
                </p>
                {premiumError && (
                  <div className="mb-3 text-xs text-danger bg-danger-bg border border-danger-border rounded-lg px-3 py-2">
                    ⚠ {premiumError}
                  </div>
                )}
                <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
                  {isAdmin ? (
                    <button
                      onClick={fetchPremiumEnhancement}
                      disabled={premiumLoading}
                      className="inline-flex items-center justify-center gap-2 text-xs font-display font-bold text-white bg-accent px-4 py-2.5 rounded-xl hover:brightness-110 active:scale-[0.98] transition-all disabled:opacity-60"
                      style={{ boxShadow: '0 4px 16px rgba(64,128,255,0.3)' }}
                    >
                      {premiumLoading ? 'Enhancing…' : 'Load Premium (Admin)'}
                    </button>
                  ) : (
                    <PayWithRazorpay
                      type="premium"
                      label="Pay ₹99 · Get job-ready resume"
                      onSuccess={fetchPremiumEnhancement}
                      onError={(msg) => setPremiumError(msg)}
                      className="inline-flex items-center justify-center gap-2 text-xs font-display font-bold text-white bg-accent px-4 py-2.5 rounded-xl hover:brightness-110 active:scale-[0.98] transition-all disabled:opacity-60"
                      style={{ boxShadow: '0 4px 16px rgba(64,128,255,0.3)' } as React.CSSProperties}
                    />
                  )}
                  {premiumLoading && !isAdmin && (
                    <p className="text-xs text-secondary animate-pulse">Enhancing your resume… (~30s)</p>
                  )}
                  {!isAdmin && <p className="text-xs text-dim">One-time · No subscription</p>}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── Premium Results ── */}
        {hasPremium && premiumResult && (
          <>
            {/* Key changes summary */}
            <div className="card result-card border-l-4 border-l-accent" style={{ animationDelay: '260ms' }}>
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2.5">
                  <div className="w-7 h-7 rounded-lg bg-accent flex items-center justify-center flex-shrink-0" style={{ boxShadow: '0 4px 12px rgba(64,128,255,0.35)' }}>
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                      <path d="M2 11l3-1L10.5 4.5a1.5 1.5 0 00-2-2L3 8l-1 3z" stroke="white" strokeWidth="1.4" strokeLinejoin="round" />
                    </svg>
                  </div>
                  <div>
                    <h2 className="section-label leading-none">Premium enhancements applied</h2>
                    <p className="text-xs text-dim mt-0.5">{premiumResult.all_improved_bullets.length} bullets rewritten · sections optimised</p>
                  </div>
                </div>
                <button
                  onClick={downloadPremiumPDF}
                  className="flex-shrink-0 flex items-center gap-1.5 text-xs font-display font-bold text-white bg-accent px-3 py-1.5 rounded-lg hover:brightness-110 transition-all"
                  style={{ boxShadow: '0 2px 8px rgba(64,128,255,0.3)' }}
                >
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <path d="M6 1.5v6M3.5 5.5l2.5 2.5 2.5-2.5M1.5 9v1A1.5 1.5 0 003 11.5h6A1.5 1.5 0 0010.5 10V9" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                  Download PDF
                </button>
              </div>
              <ul className="space-y-2">
                {premiumResult.key_changes.map((c, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-sm p-2.5 rounded-xl bg-accent-glow border border-accent-border">
                    <span className="text-accent font-bold flex-shrink-0 mt-0.5">✓</span>
                    <span className="text-primary">{c}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Section rewrites */}
            {(premiumResult.section_rewrites.summary || premiumResult.section_rewrites.skills) && (
              <div className="card result-card" style={{ animationDelay: '300ms' }}>
                <h2 className="section-label mb-4">Rewritten sections</h2>
                <div className="space-y-4">
                  {premiumResult.section_rewrites.summary && (
                    <div className="p-4 rounded-xl bg-surface border border-border">
                      <p className="text-xs font-display font-bold text-accent uppercase tracking-wider mb-2">Summary / Objective</p>
                      <p className="text-sm text-primary leading-relaxed">{premiumResult.section_rewrites.summary}</p>
                    </div>
                  )}
                  {premiumResult.section_rewrites.skills && (
                    <div className="p-4 rounded-xl bg-surface border border-border">
                      <p className="text-xs font-display font-bold text-accent uppercase tracking-wider mb-2">Skills</p>
                      <p className="text-sm text-primary leading-relaxed">{premiumResult.section_rewrites.skills}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* All improved bullets */}
            {premiumResult.all_improved_bullets.length > 0 && (
              <div className="card result-card border-l-4 border-l-accent" style={{ animationDelay: '340ms' }}>
                <div className="flex items-center gap-2.5 mb-4">
                  <div className="w-7 h-7 rounded-lg bg-accent-glow border border-accent-border flex items-center justify-center flex-shrink-0">
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                      <path d="M2 11l3-1L10.5 4.5a1.5 1.5 0 00-2-2L3 8l-1 3z" stroke="#4080FF" strokeWidth="1.4" strokeLinejoin="round" />
                    </svg>
                  </div>
                  <div>
                    <h2 className="section-label leading-none">All rewritten bullet points</h2>
                    <p className="text-xs text-dim mt-0.5">Copy and replace these in your resume</p>
                  </div>
                </div>
                <div className="space-y-3">
                  {premiumResult.all_improved_bullets.map((bullet, i) => (
                    <div key={i} className="rounded-xl bg-accent-glow border border-accent-border overflow-hidden">
                      <div className="relative p-4 pb-3">
                        <p className="text-sm font-body text-primary pr-16 leading-relaxed">
                          <span className="text-accent font-bold mr-1.5">•</span>{bullet}
                        </p>
                        <button
                          onClick={() => { navigator.clipboard.writeText(bullet); setCopied(i); setTimeout(() => setCopied(null), 2000); }}
                          className="absolute top-3 right-3 text-xs font-display font-semibold text-accent border border-accent-border bg-surface px-2.5 py-1 rounded-lg hover:bg-elevated transition-all"
                        >
                          {copied === i ? '✓ Copied' : 'Copy'}
                        </button>
                      </div>
                      {premiumResult.all_bullet_explanations[i] && (
                        <div className="px-4 pb-3 pt-0 border-t border-accent-border/40">
                          <p className="text-xs text-secondary mt-2">
                            <span className="text-accent font-semibold font-display">Why: </span>
                            {premiumResult.all_bullet_explanations[i]}
                          </p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}

        {/* ── Rewritten Bullets (from base score, shown for paid users without premium) ── */}
        {proAccess && improved_bullets && improved_bullets.length > 0 && !hasPremium && (
          <div className="card result-card border-l-4 border-l-accent" style={{ animationDelay: '280ms' }}>
            <div className="flex items-center gap-2.5 mb-4">
              <div className="w-7 h-7 rounded-lg bg-accent-glow border border-accent-border flex items-center justify-center flex-shrink-0">
                <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                  <path d="M2 11l3-1L10.5 4.5a1.5 1.5 0 00-2-2L3 8l-1 3z" stroke="#4080FF" strokeWidth="1.4" strokeLinejoin="round" />
                </svg>
              </div>
              <div>
                <h2 className="section-label leading-none">AI-rewritten bullet points</h2>
                <p className="text-xs text-dim mt-0.5">Copy and replace weak lines in your resume</p>
              </div>
            </div>
            <div className="space-y-4">
              {improved_bullets.map((bullet, i) => {
                const allKW    = [...(critKW), ...(optKW)];
                const included = keywordsInText(bullet, allKW);
                const metric   = hasMetric(bullet);
                return (
                  <div key={i} className="rounded-xl bg-accent-glow border border-accent-border overflow-hidden">
                    {/* Bullet text + copy */}
                    <div className="relative p-4 pb-3">
                      <p className="text-sm font-body text-primary pr-16 leading-relaxed">
                        <span className="text-accent font-bold mr-1.5">•</span>{bullet}
                      </p>
                      <button
                        onClick={() => copyBullet(bullet, i)}
                        className="absolute top-3 right-3 text-xs font-display font-semibold text-accent border border-accent-border bg-surface px-2.5 py-1 rounded-lg hover:bg-elevated transition-all"
                      >
                        {copied === i ? '✓ Copied' : 'Copy'}
                      </button>
                    </div>
                    {/* Badges */}
                    <div className="px-4 pb-3 flex flex-wrap gap-1.5">
                      {metric && (
                        <span className="text-xs bg-success-bg border border-success-border text-success px-2 py-0.5 rounded-full font-display font-semibold">
                          ✓ Metrics added
                        </span>
                      )}
                      {included.slice(0, 3).map(kw => (
                        <span key={kw} className="text-xs bg-accent-glow border border-accent-border text-accent px-2 py-0.5 rounded-full font-display font-semibold">
                          + {kw}
                        </span>
                      ))}
                    </div>
                    {/* Why this is better */}
                    {bullet_explanations?.[i] && (
                      <div className="px-4 pb-3 pt-0 border-t border-accent-border/40">
                        <p className="text-xs text-secondary mt-2">
                          <span className="text-accent font-semibold font-display">Why this is better: </span>
                          {bullet_explanations[i]}
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ── Section Breakdown (collapsible) ── */}
        <Collapsible
          delay="340ms"
          defaultOpen={false}
          title="Section breakdown"
          icon={
            <div className="w-7 h-7 rounded-lg bg-surface border border-border flex items-center justify-center flex-shrink-0">
              <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                <path d="M2 4h9M2 7h6M2 10h4" stroke="#8096BC" strokeWidth="1.4" strokeLinecap="round" />
              </svg>
            </div>
          }
        >
          <div className="space-y-4">
            {Object.entries(scores).map(([key, val], i) => {
              const c = scoreColor(val);
              return (
                <div key={key} className="flex items-center gap-3">
                  <span className="text-xs font-body text-secondary w-28 flex-shrink-0 truncate">{SECTION_LABELS[key] || key}</span>
                  <div className="flex-1 h-1.5 bg-surface rounded-full overflow-hidden">
                    <div className="h-full rounded-full score-bar"
                      style={{ width: `${(val / 10) * 100}%`, backgroundColor: c.bar, '--bar-delay': `${i * 80}ms` } as React.CSSProperties}
                    />
                  </div>
                  <span className={`text-xs font-display font-bold w-9 text-right ${c.text}`}>{val}/10</span>
                </div>
              );
            })}
          </div>
        </Collapsible>

        {/* ── ATS Check ── */}
        <div className="card result-card" style={{ animationDelay: '400ms' }}>
          <h2 className="section-label mb-4">ATS compatibility check</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {[
              {
                label: 'Overall ATS',
                pass: ats_verdict === 'Pass', fail: ats_verdict === 'Fail',
                desc: ats_verdict === 'Pass' ? 'Passes ATS filters' : ats_verdict === 'Borderline' ? 'May be filtered by strict ATS' : 'High risk of ATS rejection',
                impact: ats_verdict === 'Fail' ? 'Resume likely rejected before human review' : undefined,
              },
              {
                label: 'Keyword density',
                pass: (scores.skills + scores.experience) / 2 >= 6,
                fail: (scores.skills + scores.experience) / 2 < 4,
                desc: (scores.skills + scores.experience) / 2 >= 6 ? 'Good keyword coverage' : 'Too few role-specific terms',
                impact: (scores.skills + scores.experience) / 2 < 4 ? 'Low interview call-back rate' : undefined,
              },
              {
                label: 'Formatting',
                pass: scores.formatting >= 7, fail: scores.formatting < 5,
                desc: scores.formatting >= 7 ? 'Clean, parseable format' : 'Structure may break ATS parsing',
                impact: scores.formatting < 5 ? 'ATS may misread your content' : undefined,
              },
            ].map(({ label, pass, fail, desc, impact }) => (
              <div key={label} className={`p-3 rounded-xl border ${pass ? 'bg-success-bg border-success-border' : fail ? 'bg-danger-bg border-danger-border' : 'bg-warning-bg border-warning-border'}`}>
                <div className="flex items-center gap-1.5 mb-1">
                  <span className={`font-bold ${pass ? 'text-success' : fail ? 'text-danger' : 'text-warning'}`}>{pass ? '✓' : fail ? '✗' : '~'}</span>
                  <span className="font-display font-semibold text-primary text-xs">{label}</span>
                </div>
                <p className="text-xs text-secondary">{desc}</p>
                {impact && <p className={`text-xs font-semibold mt-1 ${fail ? 'text-danger' : 'text-warning'}`}>{impact}</p>}
              </div>
            ))}
          </div>
        </div>

        {/* ── India Tips (collapsible) ── */}
        <Collapsible
          delay="460ms"
          defaultOpen={false}
          title="India market tips"
          icon={<span className="text-lg leading-none w-7 text-center flex-shrink-0">🇮🇳</span>}
        >
          <ul className="space-y-2">
            {india_specific_tips.map((tip, i) => (
              <li key={i} className="flex items-start gap-3 text-sm font-body text-primary p-3 rounded-xl bg-surface border border-border">
                <span className="text-accent font-bold flex-shrink-0 mt-0.5">→</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </Collapsible>

        {/* ── Next Actions ── */}
        <div className="card result-card" style={{ animationDelay: '520ms' }}>
          <h2 className="section-label mb-4">Next actions</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <button
              onClick={copyAllImprovements}
              className="flex items-center justify-center gap-2 bg-surface border border-border hover:border-border-bright text-primary font-display font-semibold text-sm px-4 py-3 rounded-xl transition-all active:scale-[0.98]"
            >
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                <rect x="5" y="5" width="8" height="9" rx="1.5" stroke="currentColor" strokeWidth="1.3" />
                <path d="M3 10V3a1.5 1.5 0 011.5-1.5H10" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
              </svg>
              {copiedAll ? '✓ Copied!' : 'Copy all improvements'}
            </button>
            <button
              onClick={downloadReport}
              className="flex items-center justify-center gap-2 bg-accent text-white font-display font-semibold text-sm px-4 py-3 rounded-xl hover:brightness-110 transition-all active:scale-[0.98]"
              style={{ boxShadow: '0 4px 16px rgba(64,128,255,0.25)' }}
            >
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                <path d="M7.5 2v8M4.5 7.5l3 3 3-3M2 11.5v1A1.5 1.5 0 003.5 14h8a1.5 1.5 0 001.5-1.5v-1" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Download report (.txt)
            </button>
          </div>

          {/* Share */}
          <a
            href={whatsappText}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 bg-[#25D366] text-white font-display font-semibold px-5 py-3 rounded-xl hover:bg-[#20BC5A] active:scale-[0.98] transition-all wa-pulse text-sm w-full"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
            </svg>
            Share on WhatsApp
          </a>
        </div>

        {/* ── Trust strip ── */}
        <div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-xs text-dim py-2">
          {[
            'We do not store or reuse your data',
            'Files are deleted after processing',
            'No account required',
          ].map(msg => (
            <span key={msg} className="flex items-center gap-1.5">
              <svg width="11" height="11" viewBox="0 0 11 11" fill="none">
                <path d="M5.5 1L9.5 3v3C9.5 8.5 7.5 10.5 5.5 11 3.5 10.5 1.5 8.5 1.5 6V3L5.5 1z" stroke="currentColor" strokeWidth="1" strokeLinejoin="round" />
              </svg>
              {msg}
            </span>
          ))}
        </div>

      </div>

      {/* ── Sticky CTA ── */}
      <div className={`fixed bottom-0 left-0 right-0 z-40 transition-transform duration-300 ${showSticky ? 'translate-y-0' : 'translate-y-full'}`}>
        <div
          className="px-4 py-3 flex items-center justify-between gap-3 max-w-3xl mx-auto"
          style={{ background: 'rgba(10, 18, 38, 0.95)', borderTop: '1px solid rgba(64,128,255,0.2)', backdropFilter: 'blur(16px)' }}
        >
          <div className="min-w-0">
            <p className="text-xs text-secondary truncate">Score: <span className="font-semibold text-primary">{overall}/100</span> · ATS: <span className="font-semibold">{ats_verdict}</span></p>
            {projected_score && <p className="text-xs text-accent font-semibold">Apply fixes → reach {projected_score}/100</p>}
          </div>
          <button onClick={onReset} className="flex-shrink-0 btn-primary text-sm py-2.5 px-5">
            {isDemo ? 'Score my resume →' : 'Score again →'}
          </button>
        </div>
      </div>
    </>
  );
}
